version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/daniel840829/gameServer
    steps:
      - checkout
      - run: 
          name: dep install
          command: go get github.com/golang/dep/cmd/dep && dep ensure -v
      - run: 
          name: build 
          command: go build main.go
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build and Push Image daniel840829/gameplayserver
          command: |
            TAG=circleci-latest
            docker build -t  daniel840829/gameplayserver:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push daniel840829/gameplayserver:$TAG